#:schema node_modules/wrangler/config-schema.json
name = "traxelon-admin-backend"
main = "server.js"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]
minify = false

[vars]
# Add non-secret environment variables here
# FRONTEND_URL = "https://traxelon-admin.pages.dev"
